default_language_version:
    python: python3
exclude: ^notebook/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: .bumpversion.cfg
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args:
        - --recursive
        - --in-place
        - --remove-all-unused-imports
        - --remove-unused-variables
        - --expand-star-imports
        - --exclude
        - __init__.py
        - --remove-duplicate-keys
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
